import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': _englishStrings,
    'ar': _arabicStrings,
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['ar']?[key] ?? 
           key;
  }

  String translate(String key) => get(key);

  bool get isArabic => locale.languageCode == 'ar';

  static const Map<String, String> _englishStrings = {
    'app_name': 'Athar',
    'app_name_arabic': 'أثر',
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'logout_confirm': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'submit': 'Submit',
    'search': 'Search',
    'save': 'Save',
    'next': 'Next',
    'back': 'Back',
    'done': 'Done',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'username': 'Username',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'mobile': 'Mobile Number',
    'account_type': 'Account Type',
    'regular_user': 'Regular User',
    'employee': 'Lost & Found Center Employee',
    'admin': 'Administrator',
    'manager': 'Manager',
    'forgot_password': 'Forgot Password?',
    'enter_otp': 'Enter OTP',
    'send_otp': 'Send OTP',
    'verify': 'Verify',
    'reset_password': 'Reset Password',
    'invalid_credentials': 'Invalid username or password.',
    'account_pending': 'Account is pending approval. Please wait for manager confirmation.',
    'account_rejected': 'Your account request was rejected.',
    'missing_fields_search': 'Please complete all required fields before searching.',
    'missing_fields_submit': 'Please complete all required fields before submitting.',
    'invalid_location': 'You have not passed through this location. Please select a valid location from your visited routes.',
    'no_match_found': 'You will be contacted if a matching item is found later.',
    'gps_denied': 'Location permission must be enabled to activate tracking',
    'report_submitted': 'Your report has been submitted successfully.',
    'changes_saved': 'Changes updated successfully',
    'home': 'Home',
    'dashboard': 'Dashboard',
    'reports': 'Reports',
    'notifications': 'Notifications',
    'history': 'History',
    'settings': 'Settings',
    'help': 'Help & Support',
    'search_items': 'Search Items',
    'report_lost': 'Report Lost Item',
    'report_found': 'Report Found Item',
    'my_lost_reports': 'My Lost Reports',
    'my_found_reports': 'My Found Reports',
    'all_reports': 'All Reports',
    'add_report': 'Add Report',
    'requests': 'Requests',
    'pending_requests': 'Pending Requests',
    'item_type': 'Item Type',
    'item_color': 'Item Color',
    'item_location': 'Item Location',
    'upload_image': 'Upload Image',
    'take_photo': 'Take Photo',
    'choose_gallery': 'Choose from Gallery',
    'status': 'Status',
    'in_progress': 'In Progress',
    'matched': 'Matched',
    'rejected': 'Rejected',
    'mark_matched': 'Mark as Matched',
    'mark_rejected': 'Mark as Rejected',
    'approve': 'Approve',
    'reject': 'Reject',
    'update_info': 'Update Account Info',
    'change_password': 'Change Password',
    'language': 'Language',
    'arabic': 'العربية',
    'english': 'English',
    'gps_tracking_question': 'Have you been using the app since the start of your pilgrimage?',
    'yes': 'Yes',
    'no': 'No',
    'tracking_setup_complete': 'Tracking setup completed successfully',
    'add_location': 'Add Location',
    'location_name': 'Location Name',
    'date': 'Date',
    'time': 'Time',
    'transport_method': 'Transportation Method',
    'nearest_center': 'Nearest Center',
    'view_directions': 'View Directions',
    'distance': 'Distance',
    'duration': 'Duration',
    'no_reports': 'No reports found',
    'no_notifications': 'No notifications',
    'no_history': 'No history',
    'filter_by': 'Filter by',
    'all': 'All',
    'lost': 'Lost',
    'found': 'Found',
    'recent': 'Recent',
    'reports_24h': 'Reports in last 24 hours',
    'top_location': 'Top Reported Location',
    'center_submitted': 'Center Submitted',
    'manual_entry': 'Manual Entry',
    'view_delivery_locations': 'View Delivery Locations',
    'attribute_search': 'Attribute Search',
    'image_search': 'Image Search',
    'confidence_score': 'Confidence Score',
    'match_found': 'A match has been found for your lost item.',
    'status_updated': 'Your report status has been updated.',
    'maintenance_notice': 'System maintenance is currently in progress.',
    'new_report_notice': 'A new report has been submitted and needs your attention.',
    'account_approved': 'Your account has been approved. You can now log in.',
    'faqs': 'Frequently Asked Questions',
    'how_to_use': 'How to Use',
    'contact_us': 'Contact Us',
    'dashboard_guide': 'Dashboard Guide',
    'technical_support': 'Technical Support',
    'submit_reports_guide': 'How to Submit Reports',
    'user_policy': 'User Policy',
    'passport': 'Passport',
    'phone': 'Phone',
    'wallet': 'Wallet',
    'bag': 'Bag',
    'clothing': 'Clothing',
    'jewelry': 'Jewelry',
    'keys': 'Keys',
    'other': 'Other',
    'mina': 'Mina',
    'arafat': 'Arafat',
    'muzdalifah': 'Muzdalifah',
    'masjid_alharam': 'Masjid Al-Haram',
    'jamarat': 'Jamarat',
    'hotel_area': 'Hotel Area',
    'walking': 'Walking',
    'bus': 'Bus',
    'car': 'Car',
    'train': 'Train',
    'select_item_type': 'Select Item Type',
    'enter_color': 'Enter item color',
    'select_location': 'Select or enter location',
    'image_required': 'Image is required',
    'report_type': 'Report Type',
    'submission_date': 'Submission Date',
    'reporter_info': 'Reporter Information',
    'select_match': 'Select a match (optional)',
    'no_matches': 'No matching items found',
    'center_holding_item': 'Item held at',
  };

  static const Map<String, String> _arabicStrings = {
    'app_name': 'أثر',
    'app_name_arabic': 'أثر',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'logout': 'تسجيل الخروج',
    'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'submit': 'إرسال',
    'search': 'بحث',
    'save': 'حفظ',
    'next': 'التالي',
    'back': 'رجوع',
    'done': 'تم',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجاح',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'mobile': 'رقم الجوال',
    'account_type': 'نوع الحساب',
    'regular_user': 'مستخدم عادي',
    'employee': 'موظف مركز المفقودات',
    'admin': 'مدير النظام',
    'manager': 'المشرف العام',
    'forgot_password': 'نسيت كلمة المرور؟',
    'enter_otp': 'أدخل رمز التحقق',
    'send_otp': 'إرسال رمز التحقق',
    'verify': 'تحقق',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'invalid_credentials': 'اسم المستخدم أو كلمة المرور غير صحيحة.',
    'account_pending': 'حسابك قيد المراجعة. يرجى الانتظار لموافقة المشرف.',
    'account_rejected': 'تم رفض طلب حسابك.',
    'missing_fields_search': 'يرجى إكمال جميع الحقول المطلوبة قبل البحث.',
    'missing_fields_submit': 'يرجى إكمال جميع الحقول المطلوبة قبل الإرسال.',
    'invalid_location': 'لم تمر بهذا الموقع. يرجى اختيار موقع صحيح من مساراتك.',
    'no_match_found': 'سيتم التواصل معك إذا تم العثور على غرض مطابق.',
    'gps_denied': 'يجب تفعيل إذن الموقع لتفعيل التتبع',
    'report_submitted': 'تم إرسال بلاغك بنجاح.',
    'changes_saved': 'تم تحديث التغييرات بنجاح',
    'home': 'الرئيسية',
    'dashboard': 'لوحة التحكم',
    'reports': 'البلاغات',
    'notifications': 'الإشعارات',
    'history': 'السجل',
    'settings': 'الإعدادات',
    'help': 'المساعدة والدعم',
    'search_items': 'البحث عن الأغراض',
    'report_lost': 'الإبلاغ عن غرض مفقود',
    'report_found': 'الإبلاغ عن غرض موجود',
    'my_lost_reports': 'بلاغاتي المفقودة',
    'my_found_reports': 'بلاغاتي الموجودة',
    'all_reports': 'جميع البلاغات',
    'add_report': 'إضافة بلاغ',
    'requests': 'الطلبات',
    'pending_requests': 'الطلبات المعلقة',
    'item_type': 'نوع الغرض',
    'item_color': 'لون الغرض',
    'item_location': 'موقع الغرض',
    'upload_image': 'رفع صورة',
    'take_photo': 'التقاط صورة',
    'choose_gallery': 'اختيار من المعرض',
    'status': 'الحالة',
    'in_progress': 'قيد المعالجة',
    'matched': 'تم المطابقة',
    'rejected': 'مرفوض',
    'mark_matched': 'تحديد كمطابق',
    'mark_rejected': 'تحديد كمرفوض',
    'approve': 'موافقة',
    'reject': 'رفض',
    'update_info': 'تحديث معلومات الحساب',
    'change_password': 'تغيير كلمة المرور',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'English',
    'gps_tracking_question': 'هل كنت تستخدم التطبيق منذ بداية حجك؟',
    'yes': 'نعم',
    'no': 'لا',
    'tracking_setup_complete': 'تم إعداد التتبع بنجاح',
    'add_location': 'إضافة موقع',
    'location_name': 'اسم الموقع',
    'date': 'التاريخ',
    'time': 'الوقت',
    'transport_method': 'وسيلة النقل',
    'nearest_center': 'أقرب مركز',
    'view_directions': 'عرض الاتجاهات',
    'distance': 'المسافة',
    'duration': 'المدة',
    'no_reports': 'لا توجد بلاغات',
    'no_notifications': 'لا توجد إشعارات',
    'no_history': 'لا يوجد سجل',
    'filter_by': 'تصفية حسب',
    'all': 'الكل',
    'lost': 'مفقود',
    'found': 'موجود',
    'recent': 'الأحدث',
    'reports_24h': 'البلاغات في آخر 24 ساعة',
    'top_location': 'أكثر موقع للبلاغات',
    'center_submitted': 'مقدم من المركز',
    'manual_entry': 'إدخال يدوي',
    'view_delivery_locations': 'عرض مواقع التسليم',
    'attribute_search': 'البحث بالخصائص',
    'image_search': 'البحث بالصورة',
    'confidence_score': 'نسبة التطابق',
    'match_found': 'تم العثور على تطابق لغرضك المفقود.',
    'status_updated': 'تم تحديث حالة بلاغك.',
    'maintenance_notice': 'صيانة النظام جارية حالياً.',
    'new_report_notice': 'تم تقديم بلاغ جديد يحتاج انتباهك.',
    'account_approved': 'تمت الموافقة على حسابك. يمكنك الآن تسجيل الدخول.',
    'faqs': 'الأسئلة الشائعة',
    'how_to_use': 'كيفية الاستخدام',
    'contact_us': 'اتصل بنا',
    'dashboard_guide': 'دليل لوحة التحكم',
    'technical_support': 'الدعم الفني',
    'submit_reports_guide': 'كيفية تقديم البلاغات',
    'user_policy': 'سياسة المستخدم',
    'passport': 'جواز سفر',
    'phone': 'هاتف',
    'wallet': 'محفظة',
    'bag': 'حقيبة',
    'clothing': 'ملابس',
    'jewelry': 'مجوهرات',
    'keys': 'مفاتيح',
    'other': 'أخرى',
    'mina': 'منى',
    'arafat': 'عرفات',
    'muzdalifah': 'مزدلفة',
    'masjid_alharam': 'المسجد الحرام',
    'jamarat': 'الجمرات',
    'hotel_area': 'منطقة الفنادق',
    'walking': 'مشياً',
    'bus': 'حافلة',
    'car': 'سيارة',
    'train': 'قطار',
    'select_item_type': 'اختر نوع الغرض',
    'enter_color': 'أدخل لون الغرض',
    'select_location': 'اختر أو أدخل الموقع',
    'image_required': 'الصورة مطلوبة',
    'report_type': 'نوع البلاغ',
    'submission_date': 'تاريخ التقديم',
    'reporter_info': 'معلومات المُبلِّغ',
    'select_match': 'اختر تطابق (اختياري)',
    'no_matches': 'لم يتم العثور على أغراض مطابقة',
    'center_holding_item': 'الغرض محفوظ في',
  };
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
